### ISSUE TITLE
LokiStream.swift: Reuse NumberFormatter

### ISSUE THREAD

**Issue by twilightDD** [lovetodream/swift-log-loki#11]
Hi, I stumbled across this Swift package because I am looking for a similar solution. 

I noticed that at one point you create a new `NumberFormatter()` for each log entry and I would like to kindly suggest that you either pull this out of the compactMap or - better - use a factory for it. 

`NumberFormatter()` are quite expensive to create and it is recommended to reuse them as often as possible.
(see https://sarunw.com/posts/how-expensive-is-dateformatter/)
https://github.com/lovetodream/swift-log-loki/blob/fb800a495f8ee7d46796333d956dd4d92c14da40/Sources/LoggingLoki/LokiStream.swift#L10-L16

One way could be

```swift
private class LokiFormatters {
    
    static let decimalFormatter = {
        let formatter = NumberFormatter()
        formatter.numberStyle = .decimal
        formatter.groupingSeparator = ""
        #if os(macOS) || !canImport(Darwin)
        formatter.thousandSeparator = ""
        #endif
        
        return formatter
    }()
    
}


struct LokiStream: Encodable, Sendable {
    var stream: Dictionary<String, String>
    var values: Array<Array<String>>

    init(_ logs: [LokiLog], with labels: LokiLabels) {
        self.stream = labels
        self.values = logs.compactMap { log in
            let timestamp = Int64(log.timestamp.timeIntervalSince1970 * 1_000_000_000) as NSNumber
            guard let formattedTimestamp = LokiFormatters.decimalFormatter.string(from: timestamp) else {
                return nil
            }
            return [formattedTimestamp, log.message]
        }
    }
}

```

**Comment by lovetodream** [comment]
Thanks for the heads up! I'm currently doing a rewrite of the driver. I think the formatter won't be needed anymore, but if it is, I'll use a single instance.
